[package]
name = "server"
version = "0.1.0"
authors = ["Yuu Kobayashi <kb10uy@kb10uy.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "2.0"

[build-dependencies]
protoc-rust = "2.0"
